### ISSUE TITLE
Not compatible with WordPress

### ISSUE THREAD

**Issue by phamquocbuu** [Easyfood/pageAccelerator#10]
After trying adding this to my WP site:
- [WonderPlugin Slider](https://www.wonderplugin.com/wordpress-slider/) is not displayed after pajax-ing
- Cannot go back, go forward (in Chrome Browser menu)

Info:
Chrome 53.0.2785.116 (64-bit) on Mac OS
WordPress 4.6

**Comment by EvandroLG** [comment]
@cosmospham I got it your problem! You need to add `data-pageAccelerator="false"` when you want a link isn't followed by pageAccelerator.
Did you get it @cosmospham?

**Comment by phamquocbuu** [comment]
Hi EvandroLG,
I just care and click in post links, and cannot go back/forward. I want these post links have page accelerator.

**Comment by EvandroLG** [comment]
@cosmospham this the problem! pageAccelerator just follow links (<a>). pageAccelerator doesn't care about form elements.

Is GET working well? :)
