### ISSUE TITLE
Uncaught TypeError: e.body.attr is not a function

### ISSUE THREAD

**Issue by xwartz** [Easyfood/pageAccelerator#11]
After adding this to my [Hexo](http://hexo.io) blog, can't go back in Chrome.

Error message: 

`Uncaught TypeError: e.body.attr is not a function`

**Comment by EvandroLG** [comment]
it's fixed @xwartz
thank you so much ;)

any other problem, let me know, please :)

👍

**Comment by xwartz** [comment]
@EvandroLG It still doesn't work.

**Comment by EvandroLG** [comment]
I think it's fixed now :)
Can you test the latest version (0.0.5)? :)

Let me know if you've any problem 👍

**Comment by xwartz** [comment]
@EvandroLG It's working! Thanks.
