### ISSUE TITLE
CommonJS module loader does not work

### ISSUE THREAD

**Issue by wolfika** [Easyfood/pageAccelerator#13]
The global object in a browser window is `window`, which can also be referenced using `this`, like I said in my previous comment in #6 when writing a tip about how to implement this library as a universal module. However, in the module factory block, the global object is referenced by `window`, which, when loaded as a CommonJS module is `undefined`. This causes an error, and prevents the user from using this library.

Attaching screenshot:
![image](https://cloud.githubusercontent.com/assets/1512067/18633348/2baf9bba-7e7c-11e6-8c99-f2f65428eb9e.png)

FYI @EvandroLG

**Comment by EvandroLG** [comment]
hi @wolfika I think it just happens because you're runing pageAccelerator in a node envirment. In a web browser, it wouldn't happen, right?

Thanks 👍
