### ISSUE TITLE
JQuery Plugins don't work

### ISSUE THREAD

**Issue by maqsudkarimov** [Easyfood/pageAccelerator#22]
Why JQuery plugins don't work?

**Comment by EvandroLG** [comment]
I didn't understand the question @maqsudkarimov =/
Can you try again? :)

**Comment by maqsudkarimov** [comment]
When i use pageAccelerator Jquery slider don't display images.

**Comment by EvandroLG** [comment]
you need to put 'data-pageAccelerator="false"' in this links ;)
