### ISSUE TITLE
IE11 not working / Promise

### ISSUE THREAD

**Issue by Eun** [Easyfood/pageAccelerator#23]
On IE11 it does not work, simply because there is no `window.Promise`.  
I wonder why you list it as working on IE 10 because there is no `window.Promise` either

**Comment by mrmartineau** [comment]
@Eun why don't you use [Polyfill.io](https://qa.polyfill.io/v2/docs/) to add support for promises?

**Comment by Eun** [comment]
Actually I use a polyfill, now.

But the sentence on the Readme suggests that you don't need any additional stuff:
`pageAccelerator doesn't depend on jQuery, Zepto or any other library to work. You need just to include it at the end of your HTML code...`

**Comment by mrmartineau** [comment]
@Eun I would guess that pageAccelerator does not need jQuery or Zepto in order to run, it is native javascript. This does not apply to browser features which would need to be polyfilled.

**Comment by Eun** [comment]
Whatever, as I said before (for me) it suggests that you do not need any other dependencies.

A simple hint that you need polyfills for IE would be good.

**Comment by EvandroLG** [comment]
I just updated the readme. I think now it's more complete.
Thanks @Eun and @mrmartineau 👍
