### ISSUE TITLE
polyfill.io - supply chain - malicoius code

### ISSUE THREAD

**Issue by johan-st** [Easyfood/pageAccelerator#27]
Hey :)

This repo looks to have a few stars and is probably used by at least some people.
Based on the referenced sources below I do believe you might want to revise the readme though.

polyfill.io domain is used to serve malicious code.
The readme suggests using polyfil.io

references:
- https://sansec.io/research/polyfill-supply-chain-attack
- https://youtu.be/ILvNG1STUZU

Cloudflare alternative (clean):
- https://cdnjs.cloudflare.com/polyfill/

All the best!

**Comment by EvandroLG** [comment]
Thanks a million, @johan-st 
I just updated the readme ;)
