### ISSUE TITLE
 Make compatible with browserify

### ISSUE THREAD

**Issue by mef** [Easyfood/pageAccelerator#6]
It seems that pageAccelerator cannot be used with browserify.

The following code fails:

``` javascript
// client.js
var pageAccelerator = require('page-accelerator')

pageAccelerator(function(err, res) {
    console.log('page loaded', err, res)
})
```

error message: 

```
    TypeError: pageAccelerator is not a function
```

Would you consider to add compatibility with browserify? This would ease build processes, by not having to explicitely copy the `dist/page-accelerator.min.js` to a suitable location.

**Comment by paulcpederson** [comment]
@mef as a work around until this is added, you can assign the module to a different name and just call the function it adds to the window, which is hacky, but does seem to work I think?

```
// client.js
var page = require('page-accelerator')

pageAccelerator(function(err, res) {
    console.log('page loaded', err, res)
})
```

**Comment by wolfika** [comment]
I'd be glad to help with this matter, but right now I really don't have the time to do that. Anyway, I could imagine turning pageAccelerator into a universal module, which can be loaded either as a CommonJS/AMD/browserglobal module. I like to wrap my modules with a simple loader like this (ES6):

``` javascript
(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define(["pageAccelerator"], factory);
    } else if (typeof module === 'object' && module.exports) {
        module.exports = factory();
    } else {
        root.pageAccelerator = root.pageAccelerator || factory();
    }
})(this, function () {
    class PageAccelerator {
        constructor(callback) {
            // instantiation

            callback();
        }

        static initialize(callback) {
            return new PageAccelerator(callback);
        }
    }

    return PageAccelerator.initialize;
});
```

If you're interested, here's a useful article about the topic, which helped me a lot: http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/

**Comment by EvandroLG** [comment]
It makes all sense to have support to commonjs/amd. Today I'll be putting it ;)
Thanks for the sugestion 👍

**Comment by xhava** [comment]
i am using laravel, i have to put this on every page ?

```
<script src="/js/page-aceleratos.min.js"></script>
<script>
    $(function(){
        pageAccelerator();
    });
</script>
</html>
```

because i get this error:

uncaught exception: <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>
            /\* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html _/
            html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{_font-size:100%;}le

**Comment by EvandroLG** [comment]
@mef now we have support to amd and commonjs.
thanks for the suggestion! ;)

any problem, let me know, ok? :)

👍

**Comment by mef** [comment]
Thanks @EvandroLG 

Now it works with browserify, this way: 

``` javascript
// client.js
var pageAccelerator = require('page-accelerator').pageAccelerator

pageAccelerator(function(err, res) {
    console.log('page loaded', err, res)
})
```

Need to add `.pageAccelerator` after the require, for some reason. I can live with this :)

**Comment by EvandroLG** [comment]
@mef I'll improve it.
Thanks again :)
