### ISSUE TITLE
TypeError: t.on is not a function

### ISSUE THREAD

**Issue by TomasKostadinov** [Easyfood/pageAccelerator#9]
I added the script to the bottom of my site and called `pageAccelerator();`.
Everytime I click a link I get this error:

```
pageAccelerator.js:formatted:48Uncaught (in promise) TypeError: t.on is not a function(...)
     _updateHistory               @ pageAccelerator.js:formatted:48
    (anonymous function)     @ pageAccelerator.js:formatted:84
```

Which I think refers to https://github.com/Easyfood/pageAccelerator/blob/master/src/page-accelerator.js#L37

**Comment by EvandroLG** [comment]
It's fixed!
Thanks, @TomasKostadinov 👍

**Comment by TomasKostadinov** [comment]
@EvandroLG You're welcome, now it's working!
